easy_admin:
  design:
    menu:
      - label: 'Actualité'
        icon: 'newspaper-o'
        children:
          - {entity: 'Actuality', icon: 'newspaper-o', label: 'Articles'}
          - {entity: 'Category', icon: 'inbox', label: 'Catégories' }
          - {entity: 'Tag', icon: 'tags', label: 'Tags' }

      - label: 'Commentaire'
        icon: 'comments-o'
        children:
          - {entity: 'Dedicace', icon: 'comment-o', label: 'Dédicaces'}
      - label: 'Contact'
        icon: 'address-book-o'
        children:
          - {entity: 'Contact', icon: 'address-book-o', label: 'Formulaire'}
          - {entity: 'Subject', icon: 'map-marker', label: 'Destinataire'}
      - label: 'Menu'
        icon: bars
        children:
          - {entity: 'Emission', icon: 'arrow-alt-circle-right', label: 'Emission'}

