easy_admin:
  design:
    menu:
      - label: 'Actualité'
        icon: 'newspaper-o'
        children:
          - {entity: 'Actuality', icon: 'newspaper-o', label: 'Articles'}
          - {entity: 'Category', icon: 'inbox', label: 'Catégories' }
          - {entity: 'Tag', icon: 'tags', label: 'Tags' }

      - label: 'Commentaire'
        icon: 'comments-o'
        children:
          - {entity: 'Dedicace', icon: 'comment-o', label: 'Dédicaces'}

