easy_admin:
  entities:
    Actuality:
      class: App\Entity\Actuality
      list:
        fields:
          - online
          - id
          - created
          - author
          - title
          - resume
          - tags
          - category
      show:
        fields:
          - id
          - created
          - updated
          - author
          - title
          - content
          - online
          - category
          - tags
      edit:
        fields:
          - author
          - title
          - resume
          - content
          - updated
          - online
          - category
          - tags
      new:
        fields:
          - author
          - title
          - resume
          - content
          - online
          - category
          - tags
