easy_admin:
  entities:
    Subject:
      class: App\Entity\Subject
      list:
        fields:
          - id
          - online
          - name
          - email
          - contacts
      new:
        fields:
          - name
          - email
          - online
      edit:
        fields:
          - name
          - email
          - online
      show:
        fields:
          - id
          - online
          - name
          - email
          - contacts

